### ISSUE TITLE
需要完整代码

### ISSUE THREAD

**Issue by m18326612413** [Rick10119/Real-time-operation-strategy-of-virtual-power-plants#1]
您好!我对您这篇文章以及代码的实现非常感兴趣，但是文章里的部分效果图实现不了，您能否将您的完整的代码共享一下。我十分渴望能够得到您的回复，谢谢！

**Comment by Rick10119** [comment]
[感谢您对我们论文的关注，因为您没有指定具体的代码或者数据，我把所有的原始文件放在了[云盘链接](https://cloud.tsinghua.edu.cn/f/aeae134714a242c4aa54/)中，您可以下载。但是原始文件可能没有很好地注释和写readme，如果有具体的问题，可以再问我。

祝好
吕睿可

**Comment by m18326612413** [comment]
您好，非常感谢您的分享。最近看了GitHub上这篇代码，我有个疑问，在代码中初始化竞标值，更新竞标值时以及最后求实际利润时用的都是同一天(21号)的价格，而实时调节信号却是22号的。初始化竞标和更新竞标值的价格不应该是预测的价格？对此有点疑问，非常期待你的解答和指点，谢谢



---- 回复的原邮件 ----
| 发件人 | Ruike Lyu ***@***.***> |
| 日期 | 2024年11月27日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Rick10119/Real-time-operation-strategy-of-virtual-power-plants] 需要完整代码 (Issue #1) |

[感谢您对我们论文的关注，因为您没有指定具体的代码或者数据，我把所有的原始文件放在了云盘链接中，您可以下载。但是原始文件可能没有很好地注释和写readme，如果有具体的问题，可以再问我。

祝好
吕睿可

**Comment by Rick10119** [comment]
感谢您的问题，这问题问得非常好，理论上是应该像这样去进行价格预测，并且更新并且使用同一天的调频信号数据，但是我们这里做了两个假设，第一个是假设价格能够被很好地预测，所以在算例中直接使用了真实价格，因为我们的重点并不是价格的不确定性，在实际的使用中，你可以直接把具体的价格参数替换成预测的价格，这本身不会改变模型，只是参数不一样。第二个是关于调频信号，目前这样使用的原因，是因为我们并没有真实的价格那天对应的调频信号数据，而只有2020年的调频信号数据，因为PJM似乎停止了发布他们的最新调频信号，但是作为市场主体应该是能拿到最新的历史条件信号数据的。顺便说明一下信号数据并不需要模型提前预测，只是在仿真过程中模拟市场的发送市场主体的情况。我们的模型只需要对调信号的分布进行预测，这只需要使用历史的数据，所以是否对应22号并没有直接的关系。希望以上回答了你的问题。

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/27/2024 09:25 |
| To | Rick10119/Real-time-operation-strategy-of-virtual-power-plants ***@***.***> |
| Cc | Ruike Lyu ***@***.***>,
State ***@***.***> |
| Subject | Re: [Rick10119/Real-time-operation-strategy-of-virtual-power-plants] 需要完整代码 (Issue #1) |

您好，非常感谢您的分享。最近看了GitHub上这篇代码，我有个疑问，在代码中初始化竞标值，更新竞标值时以及最后求实际利润时用的都是同一天(21号)的价格，而实时调节信号却是22号的。初始化竞标和更新竞标值的价格不应该是预测的价格？对此有点疑问，非常期待你的解答和指点，谢谢



---- 回复的原邮件 ----
| 发件人 | Ruike Lyu ***@***.***> |
| 日期 | 2024年11月27日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Rick10119/Real-time-operation-strategy-of-virtual-power-plants] 需要完整代码 (Issue #1) |

[感谢您对我们论文的关注，因为您没有指定具体的代码或者数据，我把所有的原始文件放在了云盘链接中，您可以下载。但是原始文件可能没有很好地注释和写readme，如果有具体的问题，可以再问我。

祝好
吕睿可

**Comment by m18326612413** [comment]
您好，我一直对你这篇文章以及代码的内容很感兴趣。感谢你之前对我的解答，但是现在我有一个疑问。在程序的fastControl_implement里面，在实时功率分解的时候，代码中首先算出竞标值与各分布式能源最小输出功率之和的差，然后按各资源充放电成本从低到高依次参与功率分解。然而，针对各分布式能源的实际输出之和，如果并不满足竞标值，代码中直接是跳出循环，后面也没有对其做出任何惩罚。不考虑实际功率输出满足不了竞标值，这样做是否合理？这是目前我困惑的地方。非常期待作者您的回复和指点。谢谢！

**Comment by Rick10119** [comment]
一般情况下投标程序里面的约束不会让这种情况出现，但是如果预测偏差很大，例如电网AGC信号一直让放电，储能用完了电，那确实可能出现无法满足指令的情况，对此，程序给出的结果就是所有资源都按照最大可能顶上去，能顶多少是多少。然而，这种情况和一般的储能参与调频投标并没有区别，那就是顶不上了，电放完了，这可能会影响储能的调频性能得分，导致调频收益下降。我们的确在我们的新研究中测试了这种情况出现的概率，基本还是很小的，对调频性能得分影响也不大，详见https://github.com/Rick10119/Integrating-Fast-response-Capability-into-Virtual-Power-Plant-Operation-for-Ancillary-Services

**Comment by bulinbulin163** [comment]
您好，云盘链接里面的文件不存在，请问所有的原始文件还有吗？在复现的时候，遇到了些问题，想确认几个细节：
1.论文实验使用的 MATLAB、YALMIP、CPLEX/Gurobi 版本分别是什么？
2.最终结果使用的是 CPLEX 还是 Gurobi？
3.merit order 使用的 lambda/result.pi 具体来自哪个约束的 dual？
4.是否还保留 d15–d28 各 re-bid 时段的 lambda/result.pi 或 merit-order 结果？

如果方便，能否提供一个 re-bid 时段的 Bid_P、Bid_R、p_none_reg、lambda/result.pi 示例，便于核对复现结果。
非常期待您的回复，谢谢
